# This is a basic workflow to help you get started with Actions

name: Test
# name: Test
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main, develop, feat/codecov-upgrade]
  pull_request:
    branches: [main, develop,feat/codecov-upgrade]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      #      - uses: fregante/setup-git-token@v1
      #        with:
      #          token: ${{ secrets.TOKEN }}

      # - uses: actions/setup-java@v3.0.0
      #   with:
      #     distribution: "zulu"
      #     java-version: "11"

      # - uses: subosito/flutter-action@v2.3.0
      #   with:
      #     channel: "stable"

      - name: "Flutter Doctor"
        run: flutter doctor -v

      - name: "Flutter Pub Get"
        run: flutter pub get

      - name: "Flutter Format Check"
        run: dart format .

      - name: "Run Test(s)"
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.0.0
        with:
          token: ${{ secrets.CODECOV_SECRET }}
          file: coverage/lcov.info
